name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/tejas101k/kernel_xiaomi_vayu
          kernel-dir : kernel_xiaomi_vayu
          ccache : true
          ccache-size : 4G
          kernel-branch: sixteen
          config: vayu_user_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 
          aosp-clang-version: r547379
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
