name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/chaldeaprjkt/kernel_xiaomi_vayu.git
          kernel-branch: main
          config: vayu_defconfig
          arch: arm64
          other-clang-url : https://github.com/kdrag0n/proton-clang.git
          other-clang-branch : master
          aosp-gcc: false
          aosp-clang: false
          disable-lto : true
          android-version: 
          aosp-clang-version:
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
